### ISSUE TITLE
Load Balancer configuration is not correct.

### ISSUE THREAD

**Issue by rodhammond** [marcelo-ochoa/oci-swarm-cluster#1]
Load Balancer or Compute Instance docker container(s) configuration is incorrect. 
Backend Sets Health =1x Critical
Backends Health = 2x Criticals

curl -v "http://registry.mydomain.com" --resolve registry.mydomain.com:80:XXX.XXX.XXX.XXX
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: registry.mydomain.com
> Accept: */*
>
< HTTP/1.1 502 Bad Gateway
< Date: Sun, 21 Feb 2021 05:25:55 GMT
< Content-Type: text/html
< Content-Length: 161
< Connection: keep-alive
<
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center></center>
</body>
</html>

**Comment by marcelo-ochoa** [comment]
Last update on scripts which now are based on Oracle Linux 8 fixed this problem.
Line 13 on docker-compose.yml includes:
`                - traefik.http.routers.whoami.rule=(Host(`registry.mydomain.com`) && Path(`/whoami`))`
but request from Load Balancer health checks do not include host header information, so a correct must be:
`               - traefik.http.routers.whoami.rule=Path(`/whoami`)`
 but note that just after a load balancer starts the two backend will be marked as failed, this is due they are installing the software, later they will be marked as online.

**Comment by marcelo-ochoa** [comment]
Fixed with:
https://github.com/marcelo-ochoa/oci-swarm-cluster/commit/7ec8ce3f9f743c2a2050c21f2bf321722c2986d1

**Comment by rodhammond** [comment]
Marcelo,

Thanks so much for the updates.

I can reach dev-oci.xxx.yyy , but not registry.xxx.yyy

http://registry.xxx.yyy = 404 page not found

[cid:image002.png@01D70D5F.E55A6600]

[cid:image005.png@01D70D5F.E55A6600]

Thanks,
Rod

**Comment by marcelo-ochoa** [comment]
Registry is mapped only for a path /v2/
Right after deploying the stack here the expected output:
```
[root@oci-swarm-loo1-0 ~]# curl -v --resolve registry.mydomain.com:80:127.0.0.1 http://registry.mydomain.com/whoami
* Added registry.mydomain.com:80:127.0.0.1 to DNS cache
* Hostname registry.mydomain.com was found in DNS cache
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to registry.mydomain.com (127.0.0.1) port 80 (#0)
> GET /whoami HTTP/1.1
> Host: registry.mydomain.com
> User-Agent: curl/7.61.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Length: 383
< Content-Type: text/plain; charset=utf-8
< Date: Fri, 05 Mar 2021 19:19:13 GMT
< 
Hostname: 49a7b680580a
IP: 127.0.0.1
IP: 10.0.1.3
IP: 172.18.0.3
RemoteAddr: 10.0.1.18:44044
GET /whoami HTTP/1.1
Host: registry.mydomain.com
User-Agent: curl/7.61.1
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 172.18.0.1
X-Forwarded-Host: registry.mydomain.com
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: b51930688f6d
X-Real-Ip: 172.18.0.1

* Connection #0 to host registry.mydomain.com left intact
[root@oci-swarm-loo1-0 ~]# curl -v --resolve registry.mydomain.com:80:127.0.0.1 http://registry.mydomain.com/v2/
* Added registry.mydomain.com:80:127.0.0.1 to DNS cache
* Hostname registry.mydomain.com was found in DNS cache
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to registry.mydomain.com (127.0.0.1) port 80 (#0)
> GET /v2/ HTTP/1.1
> Host: registry.mydomain.com
> User-Agent: curl/7.61.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Length: 2
< Content-Type: application/json; charset=utf-8
< Date: Fri, 05 Mar 2021 19:19:21 GMT
< Docker-Distribution-Api-Version: registry/2.0
< X-Content-Type-Options: nosniff
< 
* Connection #0 to host registry.mydomain.com left intact
{}[root@oci-swarm-loo1-0 ~]# 
```
In order to Docker Registry works is necessary to enable https by uncommenting these lines:
```
                - traefik.http.routers.registry.entrypoints=https
                - traefik.http.routers.registry.tls=true
```
Marcelo.
