### ISSUE TITLE
resource deprecated

### ISSUE THREAD

**Issue by jacostag** [marcelo-ochoa/oci-swarm-cluster#2]
If you ever set or change modules or backend configuration for Terraform,

rerun this command to reinitialize your working directory. If you forget, other

commands will detect it and remind you to do so if necessary.

Warning:  "autonomous_database_id"  [DEPRECATED] The 'data.oci_database_autonomous_database_wallet' resource has been deprecated. Please use 'oci_database_autonomous_database_wallet' instead.

  on datasources.tf line 52, in data "oci_database_autonomous_database_wallet" "autonomous_database_wallet" 

  52: data "oci_database_autonomous_database_wallet" "autonomous_database_wallet" {

Error: Reference to undeclared resource

  on storage.tf line 16, in resource "oci_objectstorage_object" "oci_swarm_wallet" 

  16:   content   = oci_database_autonomous_database_wallet.autonomous_database_wallet.content

A managed resource "oci_database_autonomous_database_wallet"

autonomous_database_wallet has not been declared in the root module.

**Comment by marcelo-ochoa** [comment]
I found this warning but there is no sample code on how to rewrite using latest terraform resource :(

**Comment by jacostag** [comment]
Thanks, I will try again

**Comment by enricodeleo** [comment]
Similar issue here:
```
The 'data.oci_database_autonomous_database_wallet' resource has been
deprecated. Please use 'oci_database_autonomous_database_wallet' instead.
```

Trying to deploy a stack with 4 arm 1ocpu 6 gb. 

Any ideas?

**Comment by marcelo-ochoa** [comment]
Fixed in [commit - fix warnings](https://github.com/marcelo-ochoa/oci-swarm-cluster/commit/134c487aee224eb1a0306c67be9c29c18e2665b3)

**Comment by marcelo-ochoa** [comment]
Tested with:
Terraform v1.2.1
on linux_amd64
