### ISSUE TITLE
let's encrypt

### ISSUE THREAD

**Issue by tommorgan365** [marcelo-ochoa/oci-swarm-cluster#3]
I am having trouble with the lets encrypt ssl after creating dns records in noip.  Looking at the code do you need to create the directory structure for this entry?  - --certificatesresolvers.le.acme.storage=/data/acme.json

**Comment by marcelo-ochoa** [comment]
Tom:
   You are right.
   A quick workaround is to re-use S3 bucket created for Docker Registry repo and use it as /data directory, Docker registry only use a sub-folder named docker.
   I just committed a patch in [arm branch](https://github.com/marcelo-ochoa/oci-swarm-cluster/blob/d43090ceca04133e3c3cfc3f2b3c37ff44054a9a/scripts/docker-compose.yml#L102)
   Also I am updated traefik and portainer latest image.
   Thanks for reporting this issue.
   Marcelo.
